// GET USER
GET http://127.0.0.1:3333/api/me HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsImlhdCI6MTY5NjI2MTc1Mn0.-f4eA1L9DH39b_paJpf-Kj3sHkO1pEjvjDyNW9LFFK0
# Authorization: bearer {copy your code login here}

###

// REGISTER

POST http://127.0.0.1:3333/api/register HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test2@gmail.com",
    "password": "12345"
}

// LOGIN
###

POST http://127.0.0.1:3333/api/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "12345"
}
